<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-U5B1BD3" failures="1" tests="2" name="listener_Test" time="0.485" errors="0" timestamp="2023-04-17T12:23:43 IST">
  <testcase classname="com.listerners_Extendreports.listener_Implement" name="login" time="0.12"/>
  <testcase classname="com.listerners_Extendreports.listener_Implement" name="login1" time="0.042">
    <failure type="java.lang.AssertionError" message="expected [no-name] but found [name]">
      <![CDATA[java.lang.AssertionError: expected [no-name] but found [name]
at com.listerners_Extendreports.listener_Implement.login1(listener_Implement.java:15)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- login1 -->
</testsuite> <!-- listener_Test -->
